run:
  timeout: 2m
  tests: true

skip-dirs:
  - docs

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - gofumpt
    - gosimple
    - unused
    - ineffassign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
        - revive
        - staticcheck
        - errcheck
        - gofumpt
        - gosimple
        - unused
        - ineffassign