global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "go-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]
        labels:
          app: "alerts"

apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true